### ISSUE TITLE
Error spam on join of some players

### ISSUE THREAD

**Issue by tommasobenatti** [Ajneb97/PlayerKits#19]
Hi, after updating the plugin to the newest version (`2.24.3`), when some random players join the server this error comes in console:

```
[17:40:45 INFO]: Mr_Marco__[/xxxx:40898] logged in with entity id 251712 at ([world]-1712.5, 84.0, 17.5)
[17:40:45 WARN]: [PlayerKits] Task #772198 for PlayerKits v2.24.3 generated an exception
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
        at com.google.gson.JsonParser.parseReader(JsonParser.java:66) ~[gson-2.8.9.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:47) ~[gson-2.8.9.jar:?]
        at com.google.gson.JsonParser.parse(JsonParser.java:98) ~[gson-2.8.9.jar:?]
        at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:48) ~[bungeecord-chat-1.16-R0.4-deprecated+build.6.jar:?]
        at pk.ajneb97.managers.KitManager.getItem(KitManager.java:478) ~[PlayerKits (1).jar:?]
        at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:821) ~[PlayerKits (1).jar:?]
        at pk.ajneb97.managers.PlayerListener.darKitInicial(PlayerListener.java:61) ~[PlayerKits (1).jar:?]
        at pk.ajneb97.managers.PlayerListener$1.alTerminar(PlayerListener.java:40) ~[PlayerKits (1).jar:?]
        at pk.ajneb97.mysql.MySQL$1$2.run(MySQL.java:104) ~[PlayerKits (1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1534) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1228) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:541) ~[gson-2.8.9.jar:?]
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:61) ~[gson-2.8.9.jar:?]
        ... 16 more
```

**Comment by Ajneb97** [comment]
If you have a book in one of your kits, save the kit again, book storage was updated in latest versions.

**Comment by tommasobenatti** [comment]
Ok, thanks
