### ISSUE TITLE
when ever I use any of the commands I get a error 

### ISSUE THREAD

**Issue by jordan679** [Ajneb97/PlayerKits#20]
when ever I use any of the commands I get a error saying an internal error occurred while trying to preform this command but the command still works properly 
the  Version: 2.24.3
this is the command line output:
 [14:19:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'kits' in plugin PlayerKits v2.24.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:812) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:298) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:1913) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1878) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:68) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1109) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1088) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1081) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1064) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:983) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:285) ~[craftbukkit-1.19.2-R0.1-SNAPSHOT.jar:3593-Bukkit-c2c3908]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
	at pk.ajneb97.otros.MensajesUtils.getMensajeColor(MensajesUtils.java:26) ~[?:?]
	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:851) ~[?:?]
	at pk.ajneb97.Comando.onCommand(Comando.java:69) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at pk.ajneb97.otros.MensajesUtils.getMensajeColor(MensajesUtils.java:26) ~[?:?]
	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:851) ~[?:?]
	at pk.ajneb97.Comando.onCommand(Comando.java:69) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[bukkit-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by Speedy11CZ** [comment]
Are you using Spigot or Bukkit? Because it looks like class ChatColor from spigot is missing.
