### ISSUE TITLE
Tab completion error

### ISSUE THREAD

**Issue by themonkey2709** [Ajneb97/PlayerKits#21]
im getting an error when typing all commands with tab complete

[01:28:26 ERROR]: Exception when themonkey2709 attempted to tab complete kit edit 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/kit edit ' in plugin PlayerKits v2.24.3
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:1968) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1940) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:785) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
	at pk.ajneb97.Comando.onTabComplete(Comando.java:416) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.5.jar:git-Paper-"000cec2ab"]
	... 20 more

**Comment by themonkey2709** [comment]
the error was because my kit config was empty
