### ISSUE TITLE
Player kits not selectable

### ISSUE THREAD

**Issue by Yomamaeatstoes** [Ajneb97/PlayerKits#30]
Whenever I try using player kits, it seems to just stop and not work. I get this error msg and I don't know how to fix it. I even tried deleting my original file for it and redoing it. I am on paper 1.19.2, all the plugins are updated to the newest versions, even protocol and everything else. 

[28.01 19:21:19] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.25.1
[28.01 19:21:19] [Server] java.lang.NumberFormatExceptionFor input string: "5,470"
[28.01 19:21:19] [Server] 	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
[28.01 19:21:19] [Server] 	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
[28.01 19:21:19] [Server] 	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
[28.01 19:21:19] [Server] 	at java.lang.Double.valueOf(Double.java:614) ~[?:?]
[28.01 19:21:19] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:677) ~[PlayerKits.jar:?]
[28.01 19:21:19] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[28.01 19:21:19] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor586.execute(Unknown Source) ~[?:?]
[28.01 19:21:19] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.01 19:21:19] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.01 19:21:19] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.01 19:21:19] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3307) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
[28.01 19:21:19] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Ajneb97** [comment]
It seems like a cooldown issue
[28.01 19:21:19] [Server] java.lang.NumberFormatExceptionFor input string: "5,470"
Check your kit config and set a valid number

**Comment by Yomamaeatstoes** [comment]
That is strange, I did set the value to 0 cooldown, should I do -1 instead?
