### ISSUE TITLE
Whenever I try to purchase a kit or use my unlocked kit 

### ISSUE THREAD

**Issue by MinerMends** [Ajneb97/PlayerKits#39]
[13.08 01:22:46] [Server] [INFO] SkyWorker25 issued server command: /kit
[13.08 01:22:51] [Server] [INFO] SkyWorker25 issued server command: /kit ruby
[13.08 01:22:52] [Server] [INFO] SkyWorker25 issued server command: /kit
[13.08 01:22:53] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.24.2
[13.08 01:22:53] [Server] java.lang.IllegalArgumentExceptionNo enum constant org.bukkit.Material.STAINED_GLASS_PANE
[13.08 01:22:53] [Server] 	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
[13.08 01:22:53] [Server] 	at org.bukkit.Material.valueOf(Material.java:121) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:53] [Server] 	at pk.ajneb97.managers.InventarioConfirmacionDinero.crearInventario(InventarioConfirmacionDinero.java:39) ~[PlayerKits.jar:?]
[13.08 01:22:53] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:693) ~[PlayerKits.jar:?]
[13.08 01:22:53] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[13.08 01:22:53] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
[13.08 01:22:53] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:53] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:53] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:53] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3302) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:53] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13.08 01:22:54] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.24.2
[13.08 01:22:54] [Server] java.lang.IllegalArgumentExceptionNo enum constant org.bukkit.Material.STAINED_GLASS_PANE
[13.08 01:22:54] [Server] 	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
[13.08 01:22:54] [Server] 	at org.bukkit.Material.valueOf(Material.java:121) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:54] [Server] 	at pk.ajneb97.managers.InventarioConfirmacionDinero.crearInventario(InventarioConfirmacionDinero.java:39) ~[PlayerKits.jar:?]
[13.08 01:22:54] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:693) ~[PlayerKits.jar:?]
[13.08 01:22:54] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[13.08 01:22:54] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
[13.08 01:22:54] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:54] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:54] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:54] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3302) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:54] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13.08 01:22:56] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.24.2
[13.08 01:22:56] [Server] java.lang.IllegalArgumentExceptionNo enum constant org.bukkit.Material.STAINED_GLASS_PANE
[13.08 01:22:56] [Server] 	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.Material.valueOf(Material.java:121) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioConfirmacionDinero.crearInventario(InventarioConfirmacionDinero.java:39) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:693) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3302) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13.08 01:22:56] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.24.2
[13.08 01:22:56] [Server] java.lang.IllegalArgumentExceptionNo enum constant org.bukkit.Material.STAINED_GLASS_PANE
[13.08 01:22:56] [Server] 	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.Material.valueOf(Material.java:121) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioConfirmacionDinero.crearInventario(InventarioConfirmacionDinero.java:39) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:693) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3302) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13.08 01:22:56] [Server] [ERROR] Could not pass event InventoryClickEvent to PlayerKits v2.24.2
[13.08 01:22:56] [Server] java.lang.IllegalArgumentExceptionNo enum constant org.bukkit.Material.STAINED_GLASS_PANE
[13.08 01:22:56] [Server] 	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.Material.valueOf(Material.java:121) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioConfirmacionDinero.crearInventario(InventarioConfirmacionDinero.java:39) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:693) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at pk.ajneb97.managers.InventarioListener.clickInventario(InventarioListener.java:127) ~[PlayerKits.jar:?]
[13.08 01:22:56] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor391.execute(Unknown Source) ~[?:?]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3302) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:22:56] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

If the user has permission this error also appears.

**Comment by MinerMends** [comment]
[13.08 01:27:51] [Server] [ERROR] null
[13.08 01:27:51] [Server] org.bukkit.command.CommandExceptionUnhandled exception executing command 'kit' in plugin PlayerKits v2.24.2
[13.08 01:27:51] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:27:51] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:27:51] [Server] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1020) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
[13.08 01:27:51] [Server] 	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
[13.08 01:27:51] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2018]
[13.08 01:27:51] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13.08 01:27:51] [Server] Caused byjava.lang.NullPointerException: Cannot invoke "String.split(String)" because "id" is null
[13.08 01:27:51] [Server] 	at pk.ajneb97.managers.KitManager.getItem(KitManager.java:371) ~[PlayerKits.jar:?]
[13.08 01:27:51] [Server] 	at pk.ajneb97.managers.KitManager.claimKit(KitManager.java:821) ~[PlayerKits.jar:?]
[13.08 01:27:51] [Server] 	at pk.ajneb97.Comando.onCommand(Comando.java:132) ~[PlayerKits.jar:?]
[13.08 01:27:51] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
[13.08 01:27:51] [Server] 	... more

Seems the entire plugin is having issues. This is what happens whenever claiming a kit via command. I'm using the latest version of your plugin on the latest 1.20 Purpur btw.

**Comment by Ajneb97** [comment]
You are using PlayerKits v2.24.2...

The latest version is 2.27.1

**Comment by MinerMends** [comment]
Alrighty sorry!
